# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\12463\PycharmProjects\nju-seafile\seafile-python\Links.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(731, 456)
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(40, 50, 491, 361))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.listWidget.setFont(font)
        self.listWidget.setIconSize(QtCore.QSize(50, 50))
        self.listWidget.setObjectName("listWidget")
        self.select_all = QtWidgets.QCheckBox(Dialog)
        self.select_all.setGeometry(QtCore.QRect(40, 20, 91, 19))
        self.select_all.setObjectName("select_all")
        self.deleteLinks = QtWidgets.QPushButton(Dialog)
        self.deleteLinks.setGeometry(QtCore.QRect(560, 170, 121, 61))
        self.deleteLinks.setObjectName("deleteLinks")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.select_all.setText(_translate("Dialog", "全选"))
        self.deleteLinks.setText(_translate("Dialog", "删除上传链接"))
