# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\12463\PycharmProjects\nju-seafile\seafile-python\MainWindows.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1128, 753)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(40, 100, 891, 581))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.listWidget.setFont(font)
        self.listWidget.setIconSize(QtCore.QSize(50, 50))
        self.listWidget.setObjectName("listWidget")
        self.url_path = QtWidgets.QLineEdit(self.centralwidget)
        self.url_path.setEnabled(True)
        self.url_path.setGeometry(QtCore.QRect(90, 20, 791, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.url_path.setFont(font)
        self.url_path.setText("")
        self.url_path.setReadOnly(False)
        self.url_path.setObjectName("url_path")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(40, 20, 41, 41))
        self.back.setStyleSheet("")
        self.back.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\12463\\PycharmProjects\\nju-seafile\\seafile-python\\resource/返回.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back.setIcon(icon)
        self.back.setIconSize(QtCore.QSize(28, 28))
        self.back.setObjectName("back")
        self.select_all = QtWidgets.QCheckBox(self.centralwidget)
        self.select_all.setGeometry(QtCore.QRect(40, 70, 91, 19))
        self.select_all.setObjectName("select_all")
        self.search_input = QtWidgets.QLineEdit(self.centralwidget)
        self.search_input.setGeometry(QtCore.QRect(900, 20, 151, 41))
        self.search_input.setObjectName("search_input")
        self.search_button = QtWidgets.QToolButton(self.centralwidget)
        self.search_button.setGeometry(QtCore.QRect(1060, 20, 41, 41))
        self.search_button.setObjectName("search_button")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(950, 100, 171, 581))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(20, 20, 121, 61))
        self.pushButton.setObjectName("pushButton")
        self.uploadFolderButton = QtWidgets.QPushButton(self.frame)
        self.uploadFolderButton.setGeometry(QtCore.QRect(20, 110, 121, 61))
        self.uploadFolderButton.setObjectName("uploadFolderButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1128, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actiona = QtWidgets.QAction(MainWindow)
        self.actiona.setObjectName("actiona")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.select_all.setText(_translate("MainWindow", "全选"))
        self.search_button.setText(_translate("MainWindow", "..."))
        self.pushButton.setText(_translate("MainWindow", "生成上传链接"))
        self.uploadFolderButton.setText(_translate("MainWindow", "批量生成文件夹"))
        self.actiona.setText(_translate("MainWindow", "a"))
