# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\12463\PycharmProjects\nju-seafile\seafile-python\ShareConf.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(688, 454)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(10, 370, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.SetPassword = QtWidgets.QCheckBox(Dialog)
        self.SetPassword.setEnabled(True)
        self.SetPassword.setGeometry(QtCore.QRect(10, 20, 117, 19))
        self.SetPassword.setObjectName("SetPassword")
        self.SetExpiration = QtWidgets.QCheckBox(Dialog)
        self.SetExpiration.setEnabled(True)
        self.SetExpiration.setGeometry(QtCore.QRect(11, 137, 117, 19))
        self.SetExpiration.setObjectName("SetExpiration")
        self.dateEdit = QtWidgets.QDateEdit(Dialog)
        self.dateEdit.setEnabled(False)
        self.dateEdit.setGeometry(QtCore.QRect(30, 180, 110, 24))
        self.dateEdit.setObjectName("dateEdit")
        self.widget_2 = QtWidgets.QWidget(Dialog)
        self.widget_2.setGeometry(QtCore.QRect(10, 240, 124, 93))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton = QtWidgets.QRadioButton(self.widget_2)
        self.radioButton.setEnabled(True)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_2.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget_2)
        self.radioButton_2.setEnabled(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_2.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.widget_2)
        self.radioButton_3.setEnabled(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_2.addWidget(self.radioButton_3)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setEnabled(False)
        self.label.setGeometry(QtCore.QRect(30, 60, 171, 15))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QtCore.QRect(30, 90, 171, 24))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Dialog)
        self.SetExpiration.clicked['bool'].connect(self.dateEdit.setEnabled)
        self.SetPassword.clicked['bool'].connect(self.lineEdit.setEnabled)
        self.SetPassword.clicked['bool'].connect(self.label.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.SetPassword, self.SetExpiration)
        Dialog.setTabOrder(self.SetExpiration, self.dateEdit)
        Dialog.setTabOrder(self.dateEdit, self.radioButton)
        Dialog.setTabOrder(self.radioButton, self.radioButton_2)
        Dialog.setTabOrder(self.radioButton_2, self.radioButton_3)
        Dialog.setTabOrder(self.radioButton_3, self.pushButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "生成链接"))
        self.SetPassword.setText(_translate("Dialog", "增加密码保护"))
        self.SetExpiration.setText(_translate("Dialog", "设置过期时间"))
        self.radioButton.setText(_translate("Dialog", "预览与下载"))
        self.radioButton_2.setText(_translate("Dialog", "仅查看"))
        self.radioButton_3.setText(_translate("Dialog", "下载和上传"))
        self.label.setText(_translate("Dialog", "输入密码"))
