# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\12463\PycharmProjects\nju-seafile\seafile-python\ShareConf.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(688, 454)
        self.generateLinksButton = QtWidgets.QPushButton(Dialog)
        self.generateLinksButton.setEnabled(True)
        self.generateLinksButton.setGeometry(QtCore.QRect(10, 370, 93, 28))
        self.generateLinksButton.setObjectName("generateLinksButton")
        self.SetPassword = QtWidgets.QCheckBox(Dialog)
        self.SetPassword.setEnabled(True)
        self.SetPassword.setGeometry(QtCore.QRect(10, 20, 117, 19))
        self.SetPassword.setObjectName("SetPassword")
        self.SetExpiration = QtWidgets.QCheckBox(Dialog)
        self.SetExpiration.setEnabled(True)
        self.SetExpiration.setGeometry(QtCore.QRect(11, 137, 117, 19))
        self.SetExpiration.setObjectName("SetExpiration")
        self.widget_2 = QtWidgets.QWidget(Dialog)
        self.widget_2.setGeometry(QtCore.QRect(10, 240, 124, 93))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkAndDownload = QtWidgets.QRadioButton(self.widget_2)
        self.checkAndDownload.setEnabled(True)
        self.checkAndDownload.setObjectName("checkAndDownload")
        self.verticalLayout_2.addWidget(self.checkAndDownload)
        self.checkOnly = QtWidgets.QRadioButton(self.widget_2)
        self.checkOnly.setEnabled(True)
        self.checkOnly.setObjectName("checkOnly")
        self.verticalLayout_2.addWidget(self.checkOnly)
        self.downloadAndUpload = QtWidgets.QRadioButton(self.widget_2)
        self.downloadAndUpload.setEnabled(True)
        self.downloadAndUpload.setObjectName("downloadAndUpload")
        self.verticalLayout_2.addWidget(self.downloadAndUpload)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setEnabled(False)
        self.label.setGeometry(QtCore.QRect(30, 60, 171, 15))
        self.label.setObjectName("label")
        self.password = QtWidgets.QLineEdit(Dialog)
        self.password.setEnabled(False)
        self.password.setGeometry(QtCore.QRect(30, 90, 171, 24))
        self.password.setObjectName("password")
        self.Expiration = QtWidgets.QDateTimeEdit(Dialog)
        self.Expiration.setEnabled(False)
        self.Expiration.setGeometry(QtCore.QRect(20, 180, 194, 22))
        self.Expiration.setObjectName("Expiration")

        self.retranslateUi(Dialog)
        self.SetPassword.clicked['bool'].connect(self.password.setEnabled)
        self.SetPassword.clicked['bool'].connect(self.label.setEnabled)
        self.SetExpiration.clicked['bool'].connect(self.Expiration.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.SetPassword, self.SetExpiration)
        Dialog.setTabOrder(self.SetExpiration, self.checkAndDownload)
        Dialog.setTabOrder(self.checkAndDownload, self.checkOnly)
        Dialog.setTabOrder(self.checkOnly, self.downloadAndUpload)
        Dialog.setTabOrder(self.downloadAndUpload, self.generateLinksButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.generateLinksButton.setText(_translate("Dialog", "生成链接"))
        self.SetPassword.setText(_translate("Dialog", "增加密码保护"))
        self.SetExpiration.setText(_translate("Dialog", "设置过期时间"))
        self.checkAndDownload.setText(_translate("Dialog", "预览与下载"))
        self.checkOnly.setText(_translate("Dialog", "仅查看"))
        self.downloadAndUpload.setText(_translate("Dialog", "下载和上传"))
        self.label.setText(_translate("Dialog", "输入密码"))
